services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.4
    ports:
      - "8686:8080"
    networks:
      - proxy-net
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    command: start-dev 
    
networks:
  proxy-net:
    name: proxy-net
    driver: bridge
    external: true
