services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.5
    ports:
      - "8686:8080"
    networks:
      - proxy-network
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    command: start-dev 
    
networks:
  proxy-network:
    name: proxy-network
    driver: bridge
    external: true
