name: proxy

services:

  traefik:
    image: traefik:v2.11
    container_name: proxy  
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
      # - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "7979:80"
      - "7443:443"
      - "8881:8080"  
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_https.rule=Host(lab.locci.cloud)
      - traefik.http.routers.traefik_https.entrypoints=https
      - traefik.http.routers.traefik_https.tls=true
      - traefik.http.routers.traefik_https.service=api@internal  
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true

