version: "3.8"

services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    container_name: libsql
    restart: unless-stopped
    ports:
      - "8210:8080"
    networks:
      - libsql  
    volumes:
      - ./sqld_data:/var/lib/sqld
      - ./sqld_public_key.txt:/etc/sqld_public_key.txt
    environment:
      - SQLD_AUTH_JWT_KEY_FILE=/etc/sqld_public_key.txt

networks:
  libsql:
    name: libsql
    # external: true   
