version: "3.8"

services:
  libsql:
    image: libsql/sqld:latest
    container_name: libsql
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - libsql  
    volumes:
      - libsql-data:/var/lib/sqld

volumes:
  libsql-data:

networks:
  libsql:
    name: libsql
    # external: true   
