services:

  ghost:
    container_name: ghost
    image: docker.io/bitnami/ghost:5.84.1
    ports:
      - '2368:2368'
    volumes:
      - 'ghost_data:/bitnami/ghost'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_USERNAME=admin
      - GHOST_EMAIL=contact@miketeddyomondi.dev  
      - GHOST_PASSWORD=P@ssw0rd!#_
      - GHOST_DATABASE_HOST=mariadb.rancko.labs
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=root
      - GHOST_DATABASE_PASSWORD=${GHOST_DATABASE_PASSWORD}  
      - GHOST_DATABASE_NAME=dynasty_blog      
      - GHOST_SMTP_HOST=smtp.resend.com
      - GHOST_SMTP_PORT=465
      - GHOST_SMTP_USER=resend
      - GHOST_SMTP_PASSWORD=${GHOST_SMTP_PASSWORD}      
      - GHOST_SMTP_FROM_ADDRESS=ghost@miketeddyomondi.dev
    networks:
      - ghost    

volumes:
  ghost_data:
    name: ghost_cms_data
    driver: local

networks:
  ghost:
    name: ghost
    # external: true
